### ISSUE TITLE
saucelabs support for react unit testing 

### ISSUE THREAD

**Issue by geforce6t** [saucelabs-training/demo-js#125]
I was thinking of running my react unit/component tests on sauce cloud but most of the examples given here are based on e2e tests and I could not find any integrations of sauce with React anywhere. So is it a good idea to do this and if it is what method should be followed ?

**Comment by wswebcreation** [comment]
Hi @geforce6t 

Which tool are you using to run your React tests? Normally this is done with Jest and JSDOM, so no UI is needed, but curious how you want to do this

**Comment by geforce6t** [comment]
@wswebcreation  thanks a lot for replying ! Actually I intend to use `react-testing-library` that comes already packaged with CRA an d uses jest as the test runner ! So is it a good plan to use saucelabs integration with this ?

**Comment by wswebcreation** [comment]
Hi @geforce6t 

Well, as mentioned, when you create Unit / component tests with Jest you 9 out of 10 times don't use a UI, but a virtual DOM (by using for example JSDOM which comes with Jest). Then you run all your tests within your NodeJS environment and which doesn't need to have Sauce Labs browsers. Here's a [sample repo](https://github.com/saucelabs/sample-app-web) that we use within Sauce for our customers. You can find Unit/Component/UI tests in it. The Unit/Component tests are executed within nodeJS, the UI (functional flows through the app **and** visual checks) are executed on Sauce

Hope this helps

**Comment by geforce6t** [comment]
@wswebcreation  thanks a lot ! This is really helpful!
