### ISSUE TITLE
Fix WDIO CI

### ISSUE THREAD

**Issue by nadvolod** [saucelabs-training/demo-js#31]
I notice that you broke CI here, if it makes sense to fix it, maybe we should? I don't know or care about Nightwatch enough to do it myself haha.
![Screen Shot 2020-07-14 at 3 51 17 PM](https://user-images.githubusercontent.com/2136245/87469923-04192f80-c5ea-11ea-8034-b4f699ed9c4d.png)

**Comment by wswebcreation** [comment]
@nikolay-advolodkin 

It's not the Nightwatch commit that broke the build, it's the WDIO tests that are failing now. I'll try to fix them this week

**Comment by wswebcreation** [comment]
Well, it was not an issue, but created a new PR to add some extra logging, see https://github.com/saucelabs-training/demo-js/pull/32
