### ISSUE TITLE
Create a 'best-practices' implementation in TS

### ISSUE THREAD

**Issue by nadvolod** [saucelabs-training/demo-js#73]
My customer came back and asked me for an implementation with the following requirements:

- Using TypeScript
- Using wdio
- Running on mobile web
- Running on desktop web
- Running with visual tests
- Performance testing
- Using best practices
- In a single framework
- It will look something like this https://github.com/saucelabs-training/demo-java/tree/master/best-practice

Just letting you know that I will be working on this. Let me know if you have any thoughts @wswebcreation

**Comment by wswebcreation** [comment]
Closing this one because we already have it for a long time now
